{{ config(
    materialized='table'
) }}

WITH latest_record AS (

    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY CONTRIBUTION_WITHDRAWAL_KEY
            ORDER BY CDC_TIMESTAMP DESC
        ) AS RN

    FROM {{ source('ods','ods_con_with') }}

)

SELECT
    CONTRIBUTION_WITHDRAWAL_KEY,
    CONTRIBUTION_WITHDRAWAL_PLAN_ID,
    CONTRIBUTION_WITHDRAWAL_CLIENT_ID,
    CONTRIBUTION_WITHDRAWAL_AMOUNT,
    CONTRIBUTION_WITHDRAWAL_TYPE,
    CONTRIBUTION_WITHDRAWAL_SPS_DATE,
    CONTRIBUTION_WITHDRAWAL_FIND_DATE,
    CDC_TIMESTAMP

FROM latest_record

WHERE RN = 1
AND CDC_ACTION <> 'DELETE'